# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sean Crowley
title: Software Engineer
#email: 
website: smcrowley8.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  smcrowley8
# stackoverflow_username: "11616708"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: 
linkedin_username: "sean-m-crowley"
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  Driven and efficient worker. Adaptable and uses every opportunity to learn.

  Most skilled in: <mark>Continuous Integration</mark> 

  My other tech skills include
  - <mark>TypeScript</mark>   
  - <mark>python</mark>        
  - <mark>git</mark>              
  - <mark>bash</mark>
  - <mark>firebase</mark>         
  - <mark>docker</mark>
  - <mark>c++</mark>
  - <mark>AWS</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        title: Datirium, LLC
        link: https://datirium.com/ # https://scidap.com/
        link_text: datirium.com
        sub_title: Full Stack Developer
        caption: March 2022 - June 2025
        quote: >
          "Expert Bioinformatics. CRO-Standard Analytics. Reliable Results. Agile Delivery."
        description: | 

              - Worked in a distributed systems architecture

              - Managed Confluence pages and Jira issues according to Agile processes

              - Worked across multiple phases of the software development life cycle within multiple
                projects to: design, code, test, and document software requirements for new or enhanced
                systems

              - Automated documentation page generation and enforced documentation coverage for pull requests

              - Worked closely with Product Management and Clients to understand the business
                requirements and prepare high level tasks for design and development
              
              - Provided technical guidance and shared knowledge of design patterns and best practices to
                other team members
              
              - Collaborated with team members and stakeholders to refine solutions, and promote sharing
                of ideas

      - layout: left
        title: Narrative Science
        link: https://narrativescience.com/
        # link_text: https://narrativescience.com/
        sub_title: Software test Engineer
        caption: September 2021 - December 2021
        quote: >
          "Data Storytelling can make the world a better place. We want to see our technology used for good because we know it can make a tremendous social impact."
        description: | 
            Worked with an amazing team on keeping our automated e2e, integration, and contract tests up to date with product developement
            
              - Used <mark>Gherkin</mark> with <mark>python</mark> to make writing tests easier. Worked with <mark>AWS</mark> and <mark>docker</mark> for integrating and testing changes in a cloud based system
            
              - Automated an app auditting process using <mark>AWS CloudWatch</mark>

              - Developed a CLI runnable linter to be run as part of a test in our continous integration pipeline


  - title: Education 
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: East Stroudsburg University
        caption: 2017 - 2022
        sub_title: B.S. Computer Science, B.S. Applied Mathematics

        
  - title: Projects 
    layout: list 
    content:  
      - layout: top-middle
        title: Online Game website
        link_text: link
        link: https://board-games-3c679.web.app/
        additional_links: 
        description: |
          <mark>Web App</mark> made with <mark>nx workspaces (angular)</mark>, <mark>Clarity UI</mark>, and <mark>Firebase</mark>. 
          
          <mark>GithubActions</mark> utilized for <mark>Continuous Integration</mark>.

          This site is a personal project I'll be fleshing out in order to host online games, and document the development process for those games.
      
    content:  
      - layout: top-middle
        title: Desktop LLM App
        link_text: link
        link: https://github.com/smcrowley8/desktop-llm-app/releases
        additional_links: 
        description: |
          <mark>Desktop App</mark> made with <mark>Electron</mark>, <mark>Angular</mark>, <mark>primeNG UI</mark>, <mark>NestJS</mark>, <mark>sql</mark>, and <mark>Ollama</mark>. 
          
          <mark>GithubActions</mark> utilized for <mark>Continuous Integration</mark>.

          This desktop app is mostly a proof of concept and template for myself so I can make desktop apps with llms built into them. Ideally, this will turn into app for managing your locally run AI agents and their tasks.
          The repo is private, but builds will be stored elsewhere eventually
          
      - layout: top-middle
        title: Master Caster site
        link_text: link
        link: https://master-caster.web.app
        additional_links: 
        description: |
          <mark>Web App</mark> made with <mark>Angular</mark>, <mark>Material</mark>, and <mark>Firebase</mark>. 
          
          <mark>GithubActions</mark> utilized for <mark>Continuous Integration</mark>.

          <mark>Firebase</mark> utilized for user authentication, real-time-databasing, and hosting.

          This site is going to act as a dev log and download center for an in progress game.
          (in-progress) (currently being redeveloped with a different tech stack)

      - layout: top-middle
        title: AES project
        link: https://smcrowley8.github.io/myAES
        link_text: documentation
        additional_links: 
          - title: smcrowley8/myAES
            icon: fab fa-github
            url: https://github.com/smcrowley8/myAES
        description: |
          Python package utilizing:
          
            - <mark>poetry</mark> for package management. 
            - <mark>gitpages</mark> for documentation.          
            - <mark>click</mark> for CLI entrypoint.
            - <mark>circleCI</mark> with <mark>GithubActions</mark> for continuous integration.
            


      - layout: top-middle
        title: Settlers of Catan AI
        link: https://smcrowley8.github.io/katan-ai
        link_text: documentation
        additional_links: 
          - title: smcrowley8/katan-ai
            icon: fab fa-github
            url: https://github.com/smcrowley8/katan-ai
        description: |
          Python package utilizing:
          
            - <mark>poetry</mark> for package management. 
            - <mark>gitpages</mark> for documentation.          
            - <mark>click</mark> for CLI entrypoint.
            - <mark>circleCI</mark> with <mark>GithubActions</mark> for continuous integration.
            


      


      - layout: top-middle
        title: Chat Bot
        link: https://github.com/smcrowley8/DataSci/blob/main/ChatBot/ChatBot_howTo.ipynb
        link_text: link
        additional_links:
          - title: smcrowley8/DataSci
            icon: fab fa-github
            url: https://github.com/smcrowley8/DataSci/tree/main/ChatBot/ChatBot_howTo.ipynb
        description: |
          A non-LLM Chat bot made with <mark>python</mark>. Libraries: <mark>nltk</mark> and <mark>keras</mark> utilized for nlp and model creation/training.
          
          UI made with <mark>tkinter</mark>.


      - layout: top-middle
        title: Speech Analysis
        link: https://github.com/smcrowley8/DataSci/blob/main/simpleSpeechEmotionalRecognition/recognize%20emotion%20from%20speech%20audio.ipynb
        link_text: link
        additional_links:
          - title:  smcrowley8/DataSci
            icon: fab fa-github
            url: https://github.com/smcrowley8/DataSci/tree/main/simpleSpeechEmotionalRecognition
        description: |
          Utilized <mark>python</mark> and the library <mark>librosa</mark>. 

        

# Footer
footer_show_references: true
references_title: References on request 

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
